server:
  port: 9999  #端口

spring:
  application:
    name: microservice-config #获取配置文件的名称，不带.yml
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huamgsiyu/microservice-config.git #GitHub上配置中心的地址